"use client";

import { useState } from "react";
import { GeneratedContent } from "@/types";
import { Download, Copy, Check } from "lucide-react";

interface ExportSectionProps {
  darkMode: boolean;
  content: GeneratedContent;
  companyName: string;
}

function contentToText(content: GeneratedContent, companyName: string): string {
  const lines: string[] = [];

  lines.push(`PREPWISE AI — ${companyName.toUpperCase()} INTERVIEW PREPARATION`);
  lines.push("=".repeat(60));
  lines.push(`Generated by PrepWise AI | Built by Ranveer Pensalwar`);
  lines.push("");

  // Summary
  lines.push("📋 SUMMARY");
  lines.push("-".repeat(40));
  lines.push(content.summary.overview);
  lines.push("");
  lines.push("Key Concepts:");
  content.summary.keyConcepts.forEach((c, i) => lines.push(`  ${i + 1}. ${c}`));
  lines.push("");
  lines.push("Important Points:");
  content.summary.importantPoints.forEach((p) => lines.push(`  • ${p}`));
  lines.push("");
  lines.push("Interview Topics:");
  content.summary.interviewTopics.forEach((t) => lines.push(`  • ${t}`));
  lines.push("");

  // Flashcards
  lines.push("🃏 FLASHCARDS");
  lines.push("-".repeat(40));
  content.flashcards.forEach((f, i) => {
    lines.push(`Q${i + 1}: ${f.question}`);
    lines.push(`A${i + 1}: ${f.answer}`);
    lines.push("");
  });

  // Interview Questions
  lines.push("❓ INTERVIEW QUESTIONS");
  lines.push("-".repeat(40));
  const categories = ["technical", "behavioral", "hr", "company-specific"] as const;
  categories.forEach((cat) => {
    const qs = content.interviewQuestions.filter((q) => q.category === cat);
    if (qs.length > 0) {
      lines.push(`\n${cat.toUpperCase().replace("-", " ")}:`);
      qs.forEach((q, i) => {
        lines.push(`  ${i + 1}. ${q.question}`);
        if (q.hint) lines.push(`     Hint: ${q.hint}`);
      });
    }
  });
  lines.push("");

  // Mock Interview
  lines.push("🎤 MOCK INTERVIEW QUESTIONS");
  lines.push("-".repeat(40));
  content.mockInterview.questions.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
  lines.push("");
  lines.push("Tips:");
  content.mockInterview.tips.forEach((t) => lines.push(`  → ${t}`));
  lines.push("");

  // Roadmap
  lines.push("🗺️ PREPARATION ROADMAP");
  lines.push("-".repeat(40));
  content.roadmap.forEach((item) => {
    lines.push(`\n[${item.phase}] ${item.title} (${item.duration}) - ${item.priority.toUpperCase()} PRIORITY`);
    lines.push(`${item.description}`);
    lines.push(`Topics: ${item.topics.join(", ")}`);
  });
  lines.push("");

  // Networking
  lines.push("📧 NETWORKING MESSAGES");
  lines.push("-".repeat(40));
  content.networking.forEach((msg) => {
    lines.push(`\n[${msg.type.toUpperCase()}] Subject: ${msg.subject}`);
    lines.push(msg.message);
  });
  lines.push("");

  // Alumni
  lines.push("🔍 ALUMNI SEARCH LINKS");
  lines.push("-".repeat(40));
  content.alumniSearch.forEach((s) => {
    lines.push(`${s.description}:`);
    lines.push(`  ${s.url}`);
  });
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("Generated by PrepWise AI — prepwise.vercel.app");

  return lines.join("\n");
}

export default function ExportSection({
  darkMode,
  content,
  companyName,
}: ExportSectionProps) {
  const [copied, setCopied] = useState(false);

  const textContent = contentToText(content, companyName);

  const handleDownload = () => {
    const blob = new Blob([textContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `prepwise-${companyName.toLowerCase().replace(/\s+/g, "-")}-prep.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(textContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleCopy}
        id="copy-all-btn"
        className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium border transition-all duration-200 hover:scale-105 ${
          darkMode
            ? "border-slate-600 text-slate-300 hover:bg-slate-700"
            : "border-slate-300 text-slate-600 hover:bg-slate-100"
        }`}
      >
        {copied ? (
          <>
            <Check className="w-4 h-4 text-green-500" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            Copy All
          </>
        )}
      </button>
      <button
        onClick={handleDownload}
        id="download-btn"
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-gradient-to-r from-violet-600 to-indigo-600 text-white shadow-md shadow-violet-500/25 hover:shadow-violet-500/40 hover:scale-105 transition-all duration-200"
      >
        <Download className="w-4 h-4" />
        Download TXT
      </button>
    </div>
  );
}
